/* ============================================================
   FRONTIER AI & AGENTIC NEWS — DATA SNAPSHOT
   The dashboard reads window.DASHBOARD_DATA from this file.
   Refresh it either way:
     • In-browser  -> Settings (⚙) > add your own API key > "Refresh now"
     • Claude Code -> say "refresh the AI dashboard"
   A browser refresh persists to localStorage (survives reloads) and can be
   downloaded to overwrite this file. Nothing here contains secrets.
   ============================================================ */
window.DASHBOARD_DATA = {
  lastUpdated: "2026-07-20T17:25:00",
  version: 19,

  refreshLog: [
    { at:"2026-07-20T17:25", added: 6, note:"Claude Fable 5 goes permanent in Max/Team Premium at 50% of usage limits starting Jul 20; Pro/Team Standard keep access via usage credits plus a one-time $100 credit — ending months of on/off availability (TechTimes, Jul 18 — Anthropic catalog updated). Anthropic and Meta are in early talks to lease up to $10B of compute over two years, alongside Anthropic's existing ~$45B SpaceX compute commitment (U.S. News/Reuters, Jul 17). Moonshot AI's Kimi K3 — a 2.8T-parameter open-weight model, the largest shipped to date — takes #1 on the Frontend Code Arena ahead of both Claude Fable 5 and GPT-5.6 Sol (CNBC, Jul 17). DeepMind's Hassabis, OpenAI's Altman, and Anthropic's Amodei converge in writing on the same regulatory blueprint for frontier AI — independent pre-release testing plus a US-led standards body (Axios 'Behind the Curtain', Jul 16). OpenAI ships its first hardware, Codex Micro — a $230, 13-switch mechanical keypad for commanding coding agents, co-designed with Work Louder (TechCrunch, Jul 15). China's Implementation Opinions on Intelligent Agents take effect Jul 15 — the CAC/NDRC/MIIT's first dedicated regulatory category for AI agents, with a three-tier human-approval framework (IAPP, Jul 15). Cleared the Jul-16 🆕 flags; trimmed 8 older/superseded items (Jul-4 JadePuffer ransomware, Jul-6 xAI/SpaceXAI rebrand, Claude J-Space research, Illinois AI Safety Act, China AI-companion crackdown, midyear state-AI-law tally, Jul-7 Microsoft MAI routing, and the Jul-7 Kimi K2.7 Copilot item now superseded by the bigger Kimi K3 story). No other provider-catalog changes." },
    { at:"2026-07-17T13:51", added: 4, note:"Google rebrands NotebookLM as Gemini Notebook — 30M+ users, Gemini 3.5 + Antigravity upgrade (with a secure cloud computer per notebook for code execution) rolling to AI Pro subscribers (9to5Google, Jul 16). Bloomberg goes inside SpaceXAI's 'identity crisis' — Musk's mandate to new xAI chief Michael Nicolls: catch Anthropic, match Claude with every update (Bloomberg, Jul 16). Anthropic details million-line code migrations with Claude Code — Bun's Zig-to-Rust port (~1M lines in under two weeks, 100% of the test suite passing in CI) and a 165K-line Python-to-TypeScript weekend migration (claude.com blog, Jul 16). Codex hits 8 million users days after the GPT-5.6 launch — 7x growth in five months, usage limits reset for everyone (The New Stack, Jul 14). Cleared the Jul-15 🆕 flags; trimmed the three oldest items (Jul-2 OpenAI 5%-stake, Anthropic-Samsung chip talks, DuneSlide Cursor CVEs). No provider-catalog changes." },
    { at:"2026-07-16T15:41", added: 5, note:"xAI open-sources the entire Grok Build codebase (Apache 2.0, ~845K lines of Rust) in response to the repo-upload privacy scandal — default retention disabled Jul 12, previously retained coding data being deleted (Simon Willison, Jul 15 — Grok Build catalog entry updated). OpenAI unveils GPT-Red, a self-play RL red-team model that attacks its own systems — 84% attack success vs 13% for human red-teamers, drove GPT-5.6 Sol's direct prompt-injection failure rate to 0.05% (OpenAI, Jul 15). Anthropic + Blackstone/Hellman & Friedman/Goldman launch 'Ode with Anthropic,' a $1.5B AI-implementation joint venture (TechCrunch, Jul 15). xAI sues a user for allegedly creating CSAM with Grok — one of the first such suits by a tech company against a user (CNN, Jul 15). Gemini 3.5 Pro reportedly slips a third time with no new date; Gemini 3.6 Flash floated as a stopgap (Geeky Gadgets, Jul 15 — supersedes the Jul-13 'targets July 17' item, trimmed). Cleared the Jul-13/14 🆕 flags; trimmed 4 more oldest items (Jul-1 FTC statement + Fable-5-return, Jul-2 Sonnet-5-Azure-GA, Jul-2 Meta town hall). No other catalog changes." },
    { at:"2026-07-15T16:28", added: 6, note:"Grok Build caught uploading developers' ENTIRE Git repos — full history, committed secrets, ~27,800x the data the task needed — to an xAI cloud bucket while the privacy toggle did nothing; front page of Hacker News Jul 14, Musk promises all uploaded data 'completely and utterly deleted' (The Hacker News). Anthropic launches Claude for Teachers — free premium Claude for verified US K-12 educators, teaching-skills library + curricula mapped to standards in all 50 states (Anthropic, Jul 14 — added to the Anthropic catalog). OpenAI asks the court to make xAI pay $1M+ in legal fees over a trade-secrets suit it says 'should never have been filed', as the Apple fight revs up (Bloomberg, Jul 14). 200+ economists urge action on AI economic disruption; House Democrats hold an AI listening session as the data-center-moratorium push goes mainstream (WaPo, Jul 14). Gemini 3.5 Pro targeting Jul 17 after a ground-up rebuild — the 2.5-Pro-based architecture was scrapped over recursive tool-calling/SVG failures; no spec officially confirmed (TechTimes, Jul 13 — supersedes the Jul-4 leak item). Anthropic in exploratory talks with Samsung to build its first custom inference chip on 2nm (TechCrunch, Jul 2). Cleared the Jul-12 🆕 flag; trimmed 3 superseded/oldest items (Jul-4 Gemini leak, Jul-7 pre-GA 'cleared for launch' item, Jun-30 GuardFall). No other catalog changes." },
    { at:"2026-07-14T14:39", added: 5, note:"Recovery + refresh: the Jul-13 run was interrupted — it bumped the header and logged 4 items but never wrote them to frontier[]. Re-verified all 4 against live sources and landed them now: OpenAI admits the ChatGPT Work launch broke on four fronts after Sol deleted user files via $HOME expansion in an rm command (TechTimes, Jul 12); UK AI Security Institute found 'universal jailbreaks' unlocking autonomous cyber-exploit capabilities in GPT-5.6 Sol within hours (Fortune, Jul 10); Meta opened its first paid model API with Muse Spark 1.1 at $1.25/$4.25 per 1M — ~1/4 of Anthropic/OpenAI rates (CNBC, Jul 9); Adversa AI's GuardFall research found 10 of 11 open-source coding agents (Hermes, Goose, Cline, Aider, OpenHands…) bypassable via decades-old Bash evasion tricks (The Hacker News, Jun 30). Plus one new: Anthropic extended Claude Fable 5 subscriber access again after OpenAI's Sol release (Forbes, Jul 13). Also applied the Jul-13 trim (5 superseded items) and 🆕-flag clears that never landed; no provider-catalog changes (Gemini 3.5 Pro still Vertex-preview, July 17 launch still unconfirmed by Google)." },
    { at:"2026-07-13T14:57", added: 4, note:"OpenAI admits the Jul-9 ChatGPT Work/GPT-5.6 Sol launch broke on four fronts — usage limits burned through fast, a confusing desktop redesign, Codex-discontinuation confusion, and broken multi-agent workflows — after Sol deleted user files it wasn't authorized to touch (Jul 11); UK AI Security Institute found 'universal' pre-release jailbreaks unlocking dangerous cyber capabilities in GPT-5.6, calling it potentially worse than the Fable 5 issue (Fortune, Jul 10); Meta opened its first paid model API on Muse Spark 1.1 at roughly a quarter of Anthropic/OpenAI per-token pricing (Jul 9); GuardFall shell-injection survey found 10 of 11 open-source AI coding agents (Hermes, Goose, Cline, Aider, OpenHands, etc.) bypassable via classic Bash evasion tricks (Jun 30). Cleared Jul-10 🆕 flags; trimmed 5 older/superseded items (original Claude Science + Sonnet 5 launch cards, now covered by the Cowork/Reflect/Azure-GA follow-ups; the Jul-1 'White House nears deal' item superseded by the Jul-9 completed-gate story; the Jul-2 'new world order' opinion piece redundant with the 5%-stake item; the Jul-1 Voice Agent Builder beta item superseded by the Grok 4.5 launch)." },
    { at:"2026-07-12T12:06", added: 5, note:"OpenAI is sunsetting ChatGPT Atlas (macOS-only browser, launched Oct 2025) — stops working Aug 9, 2026, folded into the unified ChatGPT desktop app + a Chrome extension (MacRumors, Jul 10); EU Commission published its Action Plan on Cybersecurity and AI, standing up pre-market testing of frontier models by 2027 (Jul 7); Kimi K2.7 Code became GitHub Copilot's first open-weight model, expanded to Business/Enterprise (Jul 7); Bloomberg: Microsoft has begun routing some Excel/Outlook Copilot traffic to its own MAI models instead of OpenAI/Anthropic to cut costs (Jul 7); Cato AI Labs disclosed 'DuneSlide,' two CVSS-9.8 zero-click RCE flaws in Cursor's agent sandbox, patched since Cursor 3.0 (Jul 2). Cleared Jul-9 🆕 flags; trimmed 7 older/superseded items (Grok Imagine 'done', xAI dev-stack minor drop, ChatGPT Pro tier leak superseded by GA, coding-agent pricing sweep, redundant Fable-5-export-lifted item, EU AI Act simplification green light superseded by the new cybersecurity action plan, Claude apps gateway)." },
    { at:"2026-07-11T20:58", added: 4, note:"Apple sued OpenAI Jul 10 alleging trade-secret theft tied to AI hardware (Tang Tan, io fallout); OpenAI merged Codex into a unified ChatGPT desktop app + launched the ChatGPT Work agent (Jul 9); Fed chair Warsh named Marc Andreessen to co-lead a new AI productivity/jobs task force (Jul 9); Reuters via Fortune: China's Commerce Ministry weighing curbs on overseas access to its top models, incl. open-weight Qwen/Doubao/GLM-5.2 (Jul 7). Cleared Jul-8 🆕 flags; trimmed 4 older/superseded items (Grok Build launch, stale pre-launch Grok 4.5 claim, Hermes, quiet Codex model-swap)." },
    { at:"2026-07-10T14:50", added: 5, note:"GPT-5.6 goes GA Jul 9 across ChatGPT/Codex/API — Sol takes SOTA on Terminal-Bench 2.1 (88.8%), BrowseComp (92.2%) and OSWorld 2.0; catalog entry flipped preview→GA + ChatGPT/Codex/API badges updated. TechTimes: the 12-day White House gate was the first end-to-end test of the voluntary review framework. Claude gets 'Reflect' — Wrapped-style monthly recap with log-off nudges (Jul 9). Anthropic resets Claude Code usage limits Jul 10 after a week of outages. New York passes an AI bill blitz (kids' chatbot safety, training-data transparency, FAIR News Act). Cleared Jul-7 🆕 flags; trimmed 4 oldest items (Jun 23–26)." },
    { at:"2026-07-09T14:39", added: 5, note:"Grok 4.5 launches Jul 8 (Cursor-trained, Musk: 'Opus-class', $2/$6, ~80 tok/s, default in Grok Build + live in Cursor/API — catalog updated from private beta); OpenAI ships GPT-Live full-duplex voice (GPT-Live-1/mini replace Advanced Voice, delegate to GPT-5.5 — added to catalog); Anthropic's J-Space global-workspace interpretability paper (Axios); China's AI-companion Interim Measures bite Jul 15 — ByteDance/Alibaba pulling agents; EU Council final green light on AI Act simplification (Jun 29). GPT-5.6 public launch confirmed for today Jul 9 (CNBC). Cleared Jul 5–6 🆕 flags; trimmed 7 oldest items." },
    { at:"2026-07-08T13:30", added: 5, note:"GPT-5.6 cleared for public launch Thu Jul 9 (Axios/Reuters — CAISI ran extra tests after the gov-requested delay); Claude Cowork goes cloud/web/mobile Jul 7 (usage data: only 8.7% of sessions are coding); xAI officially rebrands as SpaceXAI with new logo (Jul 6); Illinois signs AI Safety Measures Act (Jul 6, effective 2028); UN Global Dialogue on AI Governance in Geneva. Updated GPT-5.6 catalog badge to the Jul 9 rollout + relabeled xAI tab SpaceXAI. Cleared Jul-4 🆕 flags." },
    { at:"2026-07-07T16:23", added: 6, note:"JadePuffer — first ransomware run end-to-end by an autonomous AI agent (Sysdig, via Langflow CVE-2025-3248); CNBC: Chinese models (GLM 5.2) within a point of Opus 4.8 at ~1/5 cost, >30% of US OpenRouter tokens; OpenAI floats 5% US-gov stake (~$42.6B) ahead of Sept IPO; Fortune: Anthropic overtakes OpenAI on revenue; White House voluntary release-standards deal near-final (FT); state-AI-law midyear tally (109 enacted). Cleared stale 🆕 flags; no provider-catalog changes." },
    { at:"2026-07-06T17:09", added: 6, note:"Same-day top-up: xAI product blitz — Voice Agent Builder beta ($0.05/min, undercuts ElevenLabs/Vapi), Speech-to-Text GA + /goal autonomous mode in Grok Build, Musk's 'Done with Grok Imagine' (Jul 5); FTC proposed AI-accuracy policy statement (Colorado AI Act 'impliedly preempted', comments thru Jul 31); GPT-5.6 Sol to run on Cerebras at 750 tok/s in July; coding-agent pricing shakeup (Copilot flex billing + $100 Max plan). Added Voice Agent Builder to the xAI catalog." },
    { at:"2026-07-06T16:31", added: 9, note:"Claude Sonnet 5 launch (Jun 30 — near-Opus agents at $2/$10 intro, 1M ctx, new Free/Pro default) + Azure/Foundry GA; Fable 5 redeployed Jul 1 with new cyber classifiers; GPT-5.6 leak shows ChatGPT Pro splitting into Luna/Terra/Sol Pro tiers (GA reportedly ~Jul 7); Gemini 3.5 Pro leaks point to Jul 17 with a fresh pretraining run; Meta town hall — agents stalled, 'Watermelon' claims GPT-5.5 parity; SpaceX–Anysphere $60B; Shazeer→OpenAI + Jumper→Anthropic; Claude apps gateway. Cleared stale 🆕 flags." },
    { at:"2026-07-01T13:12", added: 3, note:"Added Trump's June 2 frontier-AI security EO (voluntary 30-day pre-release gov access — the backdrop to the GPT-5.6/Mythos preview gates), Microsoft's seven in-house MAI models at Build 2026, and Claude Code's +50% weekly limits (matching Codex). Fable 5 now restored (Jul 1); cleared stale 🆕 flags." },
    { at:"2026-06-30T21:00", added: 6, note:"OpenAI GPT-5.6 Sol/Terra/Luna in limited preview (~20 orgs, per US gov); Anthropic ships Claude Science (pharma/labs flagship, 60+ tools); Gemini 3.5 Pro slips to July (Vertex preview only); Grok 4.5 'may exceed Opus' + monthly from-scratch cadence; Windsurf → Devin Desktop; Terminal-Bench race." },
    { at:"2026-06-30T17:00", added: 46, note:"Added xAI (Grok): Grok 4.1/4.3, Grok 4.5 private beta (V9, ~1.5T), Grok Build CLI + API, Live Search. Packaged as a shareable repo with in-browser BYOK auto-refresh." },
    { at:"2026-06-30T16:00", added: 34, note:"Multi-provider build: Anthropic/OpenAI/Google catalogs + Frontier feed (Fable 5 lifted, Gemini 3.5/Antigravity, GPT-5.5/Codex, Hermes MOA)." }
  ],

  /* ---------- FRONTIER AI NEWS (provider-agnostic, all major AI + agents) ---------- */
  frontier: [
    { date:"2026-07-18", sort:"2026-07-18T16:00", cat:"release", flag:"🆕", src:"TechTimes",
      title:"Claude Fable 5 goes permanent in Max & Team Premium — Pro users get a one-time $100 credit",
      body:"Anthropic ended months of on-and-off Fable 5 access: beginning July 20, Fable 5 is included in all Max and Team Premium plans at 50% of weekly usage limits, no extra cost. Pro and Team Standard users keep Fable 5 access through usage credits instead of plan limits, with a one-time $100 credit to offset the switch. Anthropic says demand for Fable was hard to predict, which is why it staged the rollout and extended access repeatedly before settling on this structure.",
      url:"https://www.techtimes.com/articles/320905/20260718/claude-fable-5-ends-subscription-limbo-permanent-max-credits-only-pro.htm" },
    { date:"2026-07-17", sort:"2026-07-17T18:00", cat:"policy", flag:"🆕", src:"U.S. News",
      title:"Anthropic in talks to lease up to $10B of compute from Meta",
      body:"Meta and Anthropic are discussing a compute-lease deal worth up to $10 billion over two years, with Anthropic paying in monthly increments and either side able to exit early, a source told Reuters. The talks — which Anthropic proposed in June — would let Meta generate infrastructure revenue and compete with neoclouds like CoreWeave, and would sit alongside Anthropic's existing ~$45B, three-year compute commitment to SpaceX.",
      url:"https://money.usnews.com/investing/news/articles/2026-07-17/meta-in-talks-for-10-billion-anthropic-compute-deal-nyt-reports" },
    { date:"2026-07-17", sort:"2026-07-17T14:00", cat:"release", flag:"🆕", src:"CNBC",
      title:"Moonshot's Kimi K3 — a 2.8T open-weight model — tops the Frontend Code Arena over Fable 5 and Sol",
      body:"China's Moonshot AI released Kimi K3 on July 16 — a 2.8-trillion-parameter, open-weight, multimodal reasoning model with a 1M-token context window and an always-on thinking mode, priced at $3/$15 per 1M tokens. It's the largest open-weight model shipped to date and the first to credibly compete with frontier coding agents, taking #1 on the Frontend Code Arena ahead of both Claude Fable 5 and GPT-5.6 Sol; full open weights are due by July 27.",
      url:"https://www.cnbc.com/2026/07/17/moonshot-ai-kimi-k3-model-openai-anthropic-china.html" },
    { date:"2026-07-16", sort:"2026-07-16T12:00", cat:"policy", flag:"🆕", src:"Axios",
      title:"DeepMind, OpenAI and Anthropic chiefs converge in writing on the same AI regulatory blueprint",
      body:"Demis Hassabis, Sam Altman, and Dario Amodei have each now published a plan for regulating frontier AI, and Axios finds them converging on the same diagnosis: independent testing of frontier models before public release, a standards body with authority to certify compliance and restrict dangerous systems, and US leadership over a fragmented patchwork of state or rival national regimes. Amodei goes further, pushing for an FAA-style agency with power to block unsafe launches; Altman wants an international forum for shared testing standards.",
      url:"https://www.axios.com/2026/07/16/ai-regulations-openai-anthropic-google" },
    { date:"2026-07-15", sort:"2026-07-15T10:00", cat:"release", flag:"🆕", src:"TechCrunch",
      title:"OpenAI ships its first hardware — Codex Micro, a $230 keypad for commanding coding agents",
      body:"Co-designed with keyboard maker Work Louder, Codex Micro is a 13-switch mechanical keypad with a rotary encoder, joystick, RGB backlighting, and 32 customizable icon keycaps, sold in clicky and silent versions. Dedicated keys accept or reject Codex changes, push-to-talk, and start new chats, while the rotary dial adjusts how many reasoning tokens a task gets. It lands the same week OpenAI is fighting Apple's trade-secrets suit over alleged AI-hardware poaching.",
      url:"https://techcrunch.com/2026/07/15/amid-hardware-legal-battle-openai-releases-a-230-keyboard-for-codex/" },
    { date:"2026-07-15", sort:"2026-07-15T08:00", cat:"policy", flag:"🆕", src:"IAPP",
      title:"China's Implementation Opinions on Intelligent Agents take effect — first dedicated AI-agent regulatory category",
      body:"Issued jointly by the Cyberspace Administration of China, the NDRC, and MIIT, the Implementation Opinions on the Standardized Application and Innovative Development of Intelligent Agents took effect July 15 — treating AI agents as a distinct regulatory category from generative AI for the first time anywhere. Agents must be sorted into a three-tier decision-authority structure (human-only, approval-required, autonomous) before deployment, and agents in healthcare, transportation, media, or public safety face mandatory filing, compliance testing, and product-recall provisions. It took effect alongside China's separate Interim Measures on anthropomorphic AI-companion services.",
      url:"https://iapp.org/news/a/china-s-new-ai-rules-ethics-ai-agents-and-anthropomorphic-ai" },
    { date:"2026-07-16", sort:"2026-07-16T18:00", cat:"release", flag:"", src:"9to5Google",
      title:"NotebookLM is now Gemini Notebook — Gemini 3.5 + Antigravity upgrade rolling to AI Pro",
      body:"Google rebranded NotebookLM as Gemini Notebook on July 16 and said the Gemini 3.5 + Antigravity upgrade that reached AI Ultra subscribers last month is coming to all AI Pro users on the web over the coming weeks — each notebook gets a secure cloud computer that natively writes and executes code for complex data analysis. Google says the product now has more than 30 million users across 600,000+ organizations.",
      url:"https://9to5google.com/2026/07/16/notebooklm-gemini-notebook/" },
    { date:"2026-07-16", sort:"2026-07-16T16:00", cat:"release", flag:"", src:"Bloomberg",
      title:"Inside SpaceXAI's 'identity crisis' — Musk's mandate: match Claude with every update",
      body:"Bloomberg reports that when Musk put Michael Nicolls in charge of xAI this spring, the agenda was explicit: catch up with Anthropic's Claude, with Musk wanting Grok to match Claude update-for-update. The piece portrays a company pulled between Musk's consumer ambitions for Grok and the enterprise/coding race against Anthropic and OpenAI — context for the rapid-fire Grok 4.5 launch, Grok Build open-sourcing, and the SpaceXAI rebrand.",
      url:"https://www.bloomberg.com/news/articles/2026-07-16/spacexai-identity-crisis-at-elon-musk-s-chatbot-company" },
    { date:"2026-07-16", sort:"2026-07-16T14:00", cat:"agents", flag:"", src:"Anthropic",
      title:"Anthropic details how it runs million-line code migrations with Claude Code",
      body:"A new claude.com engineering post describes how Anthropic staff migrated 10 code packages in the past month using Claude Fable 5, Opus 4.8, and dynamic workflows. Headline examples: Bun co-founder Jarred Sumner ported Bun from Zig to Rust — about a million lines produced in under two weeks, with 100% of Bun's existing test suite passing in CI before merge — and Anthropic Labs co-lead Mike Krieger migrated a Python codebase to 165,000 lines of TypeScript over a weekend.",
      url:"https://claude.com/blog/ai-code-migration" },
    { date:"2026-07-15", sort:"2026-07-15T20:00", cat:"agents", flag:"", src:"Simon Willison",
      title:"xAI open-sources Grok Build — ~845K lines of Rust under Apache 2.0 after the repo-upload scandal",
      body:"Responding to the backlash over Grok Build uploading users' entire directories (SSH keys, password-manager databases, photos) to xAI cloud servers, xAI released the complete Grok Build codebase under Apache 2.0 — roughly 844,530 lines of Rust, only ~3% vendored dependencies, rivaling OpenAI's Codex (~950K lines). The drop includes system prompts, a terminal Mermaid-diagram renderer, and tool implementations adapted from Codex and OpenCode (with attribution); xAI says default retention was disabled for all Grok Build users on July 12 and all previously retained coding data is being deleted.",
      url:"https://simonwillison.net/2026/Jul/15/grok-build/" },
    { date:"2026-07-15", sort:"2026-07-15T18:00", cat:"release", flag:"", src:"OpenAI",
      title:"OpenAI unveils GPT-Red — a self-play red-team model that attacks its own AI",
      body:"GPT-Red automates adversarial red-teaming via self-play reinforcement learning: the attacker is rewarded for eliciting failures like prompt injections while defender models are trained to resist, forcing both to keep escalating. OpenAI says it drove GPT-5.6 Sol's direct prompt-injection failure rate to 0.05% — six times fewer failures than its predecessor four months earlier — and in novel safety environments GPT-Red achieved an 84% attack success rate versus 13% for human red-teamers. The model was used in Sol's adversarial training.",
      url:"https://openai.com/index/unlocking-self-improvement-gpt-red/" },
    { date:"2026-07-15", sort:"2026-07-15T16:00", cat:"release", flag:"", src:"TechCrunch",
      title:"Anthropic and Blackstone launch 'Ode' — a $1.5B AI-implementation company",
      body:"Anthropic unveiled Ode with Anthropic, a $1.5 billion joint venture backed by Blackstone, Hellman & Friedman, Goldman Sachs, and others — a standalone company focused on deploying AI inside enterprises. The bet: the next trillion-dollar AI business is implementation — getting models actually working across large organizations — not just building the models themselves.",
      url:"https://techcrunch.com/2026/07/15/anthropic-blackstone-bet-the-next-trillion-dollar-ai-business-is-implementation-not-models/" },
    { date:"2026-07-15", sort:"2026-07-15T14:00", cat:"policy", flag:"", src:"CNN",
      title:"xAI sues a user for allegedly creating child sexual abuse material with Grok",
      body:"In one of the first lawsuits by a tech company against a user over AI-generated abuse content, xAI sued Terry Wayne Harwood, alleging he violated its terms of service 'to convert non-sexual photographs into sexually explicit images without the photograph subjects' knowledge or consent.' The filing says xAI has suspended 52,222 accounts and made 73,604 reports to NCMEC in 2026, resulting in at least 244 arrests — a notable legal front as scrutiny of Grok's image tools intensifies.",
      url:"https://www.cnn.com/2026/07/15/business/xai-sues-user-alleged-child-sexual-abuse-materials" },
    { date:"2026-07-15", sort:"2026-07-15T12:00", cat:"release", flag:"", src:"Geeky Gadgets",
      title:"Gemini 3.5 Pro slips a third time — no new date, Gemini 3.6 Flash floated as a stopgap",
      body:"Per a World of AI report, Google DeepMind has postponed Gemini 3.5 Pro for the third time since the original June target, citing underwhelming benchmark results — frequent hallucinations, inconsistent real-world workflows, and older checkpoints outperforming newer ones — amid researcher departures and internal frustration. No new date is confirmed (unofficial leaks now point to August); Google may ship Gemini 3.6 Flash as a temporary stopgap or shift focus to future models like Gemini 4.0 Flash.",
      url:"https://www.geeky-gadgets.com/gemini-3-5-pro-delayed-again/" },
    { date:"2026-07-14", sort:"2026-07-14T20:00", cat:"agents", flag:"", src:"The New Stack",
      title:"Codex hits 8 million users days after GPT-5.6 — 7x growth in five months",
      body:"OpenAI's Codex passed 8 million active users (combined with ChatGPT Work) in the days after GPT-5.6's July 9 general availability — up from under 1 million weekly users in February and 5 million in early June, with the surge running 6 million by July 12, 7 million a day later, and 8 million by Sunday. OpenAI reset usage limits for all users as capacity strained; The New Stack frames the GPT-5.6-driven surge as reshaping the coding-agent competitive map.",
      url:"https://thenewstack.io/gpt-5-6-codex-user-surge/" },
    { date:"2026-07-14", sort:"2026-07-14T18:00", cat:"agents", flag:"", src:"The Hacker News",
      title:"Grok Build uploaded entire Git repositories to xAI storage — not just the files it read",
      body:"A security researcher's wire-level analysis showed xAI's Grok Build CLI packaging developers' entire tracked repositories — full Git history, committed secrets and all — and shipping them to a Google Cloud Storage bucket, roughly 27,800x more data than the coding task actually required; a privacy toggle reportedly did nothing. The findings hit the Hacker News front page July 14, and Musk responded by promising all previously uploaded user data would be 'completely and utterly deleted.'",
      url:"https://thehackernews.com/2026/07/grok-build-uploads-entire-git.html" },
    { date:"2026-07-14", sort:"2026-07-14T16:00", cat:"release", flag:"", src:"Anthropic",
      title:"Anthropic launches Claude for Teachers — free premium Claude for US K-12 educators",
      body:"Verified US K-12 educators get a free year of premium Claude (sign-ups through June 30, 2027), a library of teaching skills, and a Learning Commons connection with evidence-based curricula mapped to academic standards in all 50 states. Ships with an AI Fluency for K-12 Teachers course co-created with Teach For America and a train-the-trainer module with the American Federation of Teachers; data isn't used to train models, with FERPA-aligned student-privacy protections.",
      url:"https://www.anthropic.com/news/claude-for-teachers" },
    { date:"2026-07-14", sort:"2026-07-14T14:00", cat:"policy", flag:"", src:"Bloomberg",
      title:"OpenAI asks court to make xAI pay $1M+ in legal fees as the Apple trade-secrets fight revs up",
      body:"OpenAI asked a judge to declare that xAI's trade-secret-theft lawsuit 'should never have been filed' and to recoup more than $1 million in legal expenses from Musk's company, while xAI gave notice it intends to appeal its repeatedly dismissed claims that OpenAI poached employees and encouraged them to steal confidential information — the Musk–Altman feud escalating just as OpenAI digs in against Apple's own July 10 trade-secrets suit.",
      url:"https://www.bloomberg.com/news/articles/2026-07-14/openai-s-feud-with-xai-carries-on-as-apple-secrets-fight-revs-up" },
    { date:"2026-07-14", sort:"2026-07-14T12:00", cat:"policy", flag:"", src:"Washington Post",
      title:"AI's economic reckoning: 200+ economists urge action as House Democrats take up AI policy",
      body:"The Washington Post's AI brief flags a widening economic-policy front: more than 200 economists and AI luminaries signed a call to address AI-driven social and economic disruption, the House Democratic Caucus held a July 14 listening session on AI policy, and the push for a data-center moratorium is going mainstream in the party.",
      url:"https://www.washingtonpost.com/wp-intelligence/ai-tech-brief/2026/07/14/ai-tech-brief-ais-economic-reckoning/" },
    { date:"2026-07-13", sort:"2026-07-13T18:00", cat:"release", flag:"", src:"Forbes",
      title:"Anthropic extends Claude Fable 5 access again after OpenAI's Sol release",
      body:"Anthropic extended subscriber access to Claude Fable 5 for the second time in a week — a move Forbes frames as an apparent response to OpenAI's GPT-5.6 Sol launch, keeping Anthropic's Mythos-class flagship in front of paying users as the model wars escalate.",
      url:"https://www.forbes.com/sites/tylerroush/2026/07/13/ai-model-wars-anthropic-extends-fable-access-again-after-openais-sol-release/" },
    { date:"2026-07-12", sort:"2026-07-12T14:00", cat:"agents", flag:"", src:"TechTimes",
      title:"OpenAI admits the ChatGPT Work launch went wrong — after Sol deleted user files",
      body:"OpenAI engineer Thibault Sottiaux acknowledged four failures in the July 9 launch: GPT-5.6 Sol at max settings burning through usage credits far faster than GPT-5.5, a confusing one-shot desktop redesign, Codex users concluding their tool was deprecated, and broken multi-agent workflows. The admission followed reports — including from AI investor Matt Shumer — that a Sol agent deleted files on a user's Mac by expanding the HOME variable inside an rm command, a scenario OpenAI's own System Card documented before release. A remediation update is expected the week of July 14.",
      url:"https://www.techtimes.com/articles/320198/20260712/chatgpt-work-launch-went-wrong-gpt-56-sol-deleted-user-files-without-permission.htm" },
    { date:"2026-07-10", sort:"2026-07-10T21:00", cat:"policy", flag:"", src:"Fortune",
      title:"UK AI Security Institute finds 'universal jailbreaks' unlocking dangerous cyber capabilities in GPT-5.6",
      body:"UK AISI researchers found universal jailbreaks in GPT-5.6 Sol within hours of release, unlocking the model's ability to autonomously discover software vulnerabilities and conduct exploits — potentially more severe than the comparable Fable 5 flaw that triggered June's US export controls, since it enables direct autonomous attacks rather than just vulnerability identification. OpenAI says it reproduced and mitigated the specific jailbreaks; policy researchers flag the apparent double standard of no similar US action against GPT-5.6.",
      url:"https://fortune.com/2026/07/10/openai-gpt-5-6-sol-jailbreaks-cyber-attacks-similar-to-security-flaw-that-led-u-s-government-to-force-anthropic-to-disable-fable-5/" },
    { date:"2026-07-10", sort:"2026-07-10T20:00", cat:"policy", flag:"", src:"CNBC",
      title:"Apple sues OpenAI over alleged trade secret theft tied to AI hardware",
      body:"Apple filed suit against OpenAI and two former Apple employees in federal court in Northern California on July 10, alleging a scheme 'at every level, from members of its Technical Staff to its Chief Hardware Officer' to steal Apple trade secrets — including claims OpenAI hardware chief Tang Tan (an ex-Apple VP) coached departing Apple staff on evading exit security, and that one former employee, Chang Liu, took an Apple laptop. The suit marks a sharp break from the 2024 ChatGPT-on-iPhone partnership, chilled since OpenAI's $6.4B acquisition of Jony Ive's hardware startup io. OpenAI denies the allegations.",
      url:"https://www.cnbc.com/2026/07/10/apple-openai-lawsuit-trade-secrets.html" },
    { date:"2026-07-10", sort:"2026-07-10T16:00", cat:"release", flag:"", src:"MacRumors",
      title:"OpenAI shuts down ChatGPT Atlas browser eight months after launch",
      body:"OpenAI confirmed it's sunsetting ChatGPT Atlas, its macOS-only AI browser launched October 21, 2025 — the app stops working August 9, 2026. Browser-based agentic features move into the unified ChatGPT desktop app (alongside the new Work and Codex tabs) plus a ChatGPT/Codex Chrome extension; Atlas never shipped for Windows, iOS, or Android. Bookmarks, history, saved passwords, and cookies won't migrate automatically — OpenAI is telling users to export anything they need before the shutoff.",
      url:"https://www.macrumors.com/2026/07/10/openais-chatgpt-atlas-browser-shutting-down/" },
    { date:"2026-07-10", sort:"2026-07-10T12:00", cat:"agents", flag:"", src:"Startup Fortune",
      title:"Anthropic resets Claude Code usage limits again after a rough week of outages",
      body:"Anthropic quietly reset Claude Code's 5-hour and weekly usage limits for every user on July 10 — the latest in a string of resets following a stretch of outages. Pro, Max, Team, and seat-based Enterprise users all got a clean slate, a goodwill move as the coding-agent wars make reliability and rate limits a competitive front.",
      url:"https://startupfortune.com/anthropic-resets-claude-code-usage-limits-again-after-a-rough-week-of-outages/" },
    { date:"2026-07-10", sort:"2026-07-10T10:00", cat:"policy", flag:"", src:"Transparency Coalition",
      title:"New York lawmakers pass an AI bill blitz — kids' chatbot safety, training-data transparency, FAIR News Act",
      body:"The Transparency Coalition's July 10 legislative update tallies New York's end-of-session sweep: legislators passed a kids' chatbot-safety bill, an AI training-data transparency act, the FAIR News Act, a data-center moratorium, and a ban on AI-assisted surveillance pricing — a package now headed to Gov. Hochul as states keep legislating around the federal preemption push.",
      url:"https://www.transparencycoalition.ai/news/ai-legislative-update-july10-2026" },
    { date:"2026-07-09", sort:"2026-07-09T20:00", cat:"release", flag:"", src:"CNBC",
      title:"Meta opens its first paid model API — Muse Spark 1.1 undercuts rivals at $1.25/$4.25",
      body:"Meta launched Muse Spark 1.1 on July 9 — a multimodal reasoning model with a 1M-token context window built for agentic tasks, tool use, computer use, and coding — and opened the Meta Model API to developers in US public preview at $1.25/$4.25 per 1M tokens ($20 free credits for new accounts). Zuckerberg pitched the pricing as roughly a quarter of what Anthropic and OpenAI charge for comparable models, and broke a three-year X posting silence to announce it.",
      url:"https://www.cnbc.com/2026/07/09/meta-jumps-into-ai-coding-market-to-chase-anthropic-and-openai.html" },
    { date:"2026-07-09", sort:"2026-07-09T19:00", cat:"release", flag:"", src:"OpenAI",
      title:"OpenAI launches ChatGPT Work and merges Codex into one desktop app",
      body:"OpenAI shipped ChatGPT Work on July 9 — an agent that takes a goal, gathers information across your connected apps and files, breaks the job into steps, and finishes it on its own, producing sheets, slides, and documents. Alongside it, Codex merged into a new unified ChatGPT desktop app (Mac/Windows) sitting next to Chat and Work, gaining inline diff editing, GitHub pull-request review in a sidebar, faster GPT-5.6-powered Computer Use, and multi-repo projects. Chat, Work, and Codex are available on every plan, including Free.",
      url:"https://openai.com/index/chatgpt-for-your-most-ambitious-work/" },
    { date:"2026-07-09", sort:"2026-07-09T18:00", cat:"release", flag:"", src:"OpenAI",
      title:"GPT-5.6 is live — Sol/Terra/Luna hit GA across ChatGPT, Codex & the API",
      body:"OpenAI made GPT-5.6 generally available on July 9, with global rollout over 24 hours. ChatGPT Plus/Pro/Business/Enterprise get Sol at medium-and-up reasoning effort; Free and Go users get Terra; Codex and the API expose all three tiers. Sol posts new SOTA numbers: Terminal-Bench 2.1 at 88.8% (91.9% Ultra config, ahead of Claude Fable 5's 83.4%), BrowseComp 92.2%, OSWorld 2.0 62.6%. Pricing/1M: Sol $5/$30, Terra $2.50/$15, Luna $1/$6.",
      url:"https://openai.com/index/gpt-5-6/" },
    { date:"2026-07-09", sort:"2026-07-09T17:00", cat:"policy", flag:"", src:"TechTimes",
      title:"GPT-5.6's 12-day White House gate — first end-to-end test of the voluntary review framework",
      body:"GPT-5.6's path to public launch — June 26 limited preview at the government's request, CAISI's additional testing and meetings, then the July 9 clearance — marks the first complete run of the voluntary pre-release review regime created by Trump's June frontier-AI security EO, setting the template other labs' flagships are now expected to follow.",
      url:"https://www.techtimes.com/articles/319979/20260709/gpt-56-goes-public-after-12-day-white-house-gate-tests-voluntary-ai-framework.htm" },
    { date:"2026-07-09", sort:"2026-07-09T16:00", cat:"release", flag:"", src:"MacRumors",
      title:"Claude gets 'Reflect' — a monthly Wrapped-style recap that nudges you to log off",
      body:"Anthropic added Reflect to Claude (beta, Free/Pro/Max with memory on): a Settings dashboard showing the topics you spent time on, your most active day and peak hour, and observations about how you work with Claude, with 1–12-month lookbacks and suggestions built on Anthropic's 4D AI-fluency framework. It also adds quiet hours and take-a-break nudges; incognito chats and health-integration conversations are excluded.",
      url:"https://www.macrumors.com/2026/07/09/anthropic-reflect-claude-tracking/" },
    { date:"2026-07-09", sort:"2026-07-09T15:00", cat:"policy", flag:"", src:"Axios",
      title:"Fed taps Marc Andreessen to co-lead a new AI productivity-and-jobs task force",
      body:"Fed Chair Kevin Warsh named leaders of five outside task forces on July 9 as part of a push to modernize the central bank; a16z's Marc Andreessen co-leads (with Jones and Microsoft Xbox chief Asha Sharma) the panel evaluating how AI and other 'new general-purpose technologies' affect the labor market and productivity growth. Recommendations to the FOMC are due by end of 2026 — with implications for how the Fed models potential GDP growth.",
      url:"https://www.axios.com/2026/07/09/fed-warsh-task-force-andreessen" },
    { date:"2026-07-08", sort:"2026-07-08T18:00", cat:"release", flag:"", src:"SpaceXAI",
      title:"Grok 4.5 launches — Musk's 'Opus-class' Cursor-trained flagship at $2/$6",
      body:"SpaceXAI released Grok 4.5 on July 8 — its strongest model ever, trained alongside Cursor and tuned for coding (incl. Rust/C++), agentic tasks, and knowledge work. Served at ~80 tok/s and resolving tasks in ~15,954 output tokens on average (~4.2x fewer than Opus 4.8 max); $2/$6 per 1M tokens. Default in Grok Build, live in Cursor (all plans), the SpaceXAI console/API, and major gateways; public rollout July 9, EU mid-July. Musk: 'an Opus-class model, but faster, more token-efficient and lower cost.'",
      url:"https://x.ai/news/grok-4-5" },
    { date:"2026-07-08", sort:"2026-07-08T16:00", cat:"release", flag:"", src:"OpenAI",
      title:"OpenAI ships GPT-Live — full-duplex voice that listens while it talks",
      body:"GPT-Live-1 (paid tiers) and GPT-Live-1 mini (free) began rolling out July 8 across iOS, Android, and chatgpt.com, replacing Advanced Voice: full-duplex models that keep processing your audio while speaking — backchannels ('mhmm'), quick interruptions, knowing when to stay quiet — and delegate harder questions to GPT-5.5 in the background without breaking conversational flow. Landed one day ahead of the broad GPT-5.6 release.",
      url:"https://openai.com/index/introducing-gpt-live/" },
    { date:"2026-07-07", sort:"2026-07-07T21:00", cat:"policy", flag:"", src:"European Commission",
      title:"EU unveils Action Plan on Cybersecurity and AI — pre-market testing for frontier models",
      body:"The European Commission published its Action Plan on Cybersecurity and Artificial Intelligence on July 7, laying out nine actions across three goals: making frontier AI safe for cyber defense, hardening critical infrastructure, and scaling Europe's own AI-security capacity. Centerpiece is a dedicated EU evaluation capacity (targeted operational by 2027, working with the AI Office) to test advanced models before EU market entry, plus a Q4-2026 'European Blueprint' with ENISA for organizing cybersecurity access to frontier models and contingency plans for joint procurement if access to a frontier model becomes critical.",
      url:"https://commission.europa.eu/news-and-media/news/new-eu-plan-address-risks-and-opportunities-advanced-ai-cybersecurity-2026-07-07_en" },
    { date:"2026-07-07", sort:"2026-07-07T19:00", cat:"policy", flag:"", src:"Fortune",
      title:"China weighs restricting overseas access to its most advanced AI models",
      body:"Per a Reuters report, China's Ministry of Commerce has spent the past month meeting with Alibaba, ByteDance, and Z.ai over whether to curb foreign access to the country's top-tier AI models — covering both proprietary systems and open-weight releases like Qwen, Doubao, and GLM-5.2. Options floated range from a public-release bar to domestic-use-only restrictions, plus making leaks of proprietary AI tech a national-security offense. Nothing decided yet, but it mirrors Washington's own model-control instincts.",
      url:"https://fortune.com/2026/07/08/china-mulls-limiting-foreign-access-advanced-ai-models/" },
    { date:"2026-07-07", sort:"2026-07-07T16:00", cat:"agents", flag:"", src:"TechCrunch",
      title:"Claude Cowork goes cloud — web, iOS & Android, tasks that outlive your laptop",
      body:"Anthropic is moving Cowork sessions to the cloud: start a task on desktop, close the lid, review the result from your phone — scheduled tasks run even with no device online. Beta rolls out to Max users over the coming weeks. Anthropic's own data (1.2M sessions, 600K+ orgs): only 8.7% of Cowork use is software engineering — 90%+ is general knowledge work.",
      url:"https://techcrunch.com/2026/07/07/the-coding-agent-wars-are-spilling-into-the-rest-of-the-office-claude-cowork/" },
    { date:"2026-07-07", sort:"2026-07-07T14:00", cat:"policy", flag:"", src:"UN News",
      title:"UN Global Dialogue on AI Governance opens in Geneva amid 'catastrophic harm' warnings",
      body:"The first UN Global Dialogue on AI Governance convened July 6-7 in Geneva, pushing for international coordination on frontier-model risks as officials warned of potential 'catastrophic harm' from ungoverned advanced AI — the multilateral counterpoint to Washington's voluntary lab-by-lab deals.",
      url:"https://news.un.org/en/story/2026/07/1167862" },
    { date:"2026-07-07", sort:"2026-07-07T12:00", cat:"release", flag:"", src:"CNBC",
      title:"Chinese AI models gain ground with US companies as frontier costs surge",
      body:"GLM 5.2 lands within a percentage point of Opus 4.8 on a closely watched agentic benchmark at roughly a fifth of the cost, and Chinese models' share of the tokens US companies route through OpenRouter has held above 30% every week since Feb 8 — peaking at 46% — as OpenAI/Anthropic pricing climbs.",
      url:"https://www.cnbc.com/2026/07/07/chinese-ai-models-costs-us-openai-anthropic.html" },
  ],

  /* ---------- PROVIDERS ---------- */
  providers: {

    anthropic: {
      label:"Anthropic (Claude)", accent:"#d97757",
      models: [
        { name:"Claude Code (CLI)", access:["subscription","api"], iface:"cli", status:"live",
          badge:"Opus 4.8 · Sonnet 5 · Haiku 4.5 · Fable 5*",
          blurb:"Anthropic's official terminal agent. Runs on a Claude Pro/Max subscription OR API billing. Fable 5 is now permanent in Max/Team Premium at 50% of usage limits (as of Jul 20); Pro/Team Standard access it via usage credits (*).",
          url:"https://www.anthropic.com/claude-code" },
        { name:"Claude Science", access:["subscription"], iface:"web", status:"new", badge:"agentic research · 60+ sci tools",
          blurb:"New flagship research app for scientists & pharma — autonomous literature review, computational biology, and drug-discovery workflows over 60+ databases. Included for all paid Claude subscribers; partners incl. Novo Nordisk, AstraZeneca, Eli Lilly.",
          url:"https://www.anthropic.com/news" },
        { name:"Claude for Teachers", access:["subscription"], iface:"web", status:"new", badge:"free · US K-12 educators",
          blurb:"Free premium Claude for verified US K-12 educators (launched Jul 14) — teaching-skills library + Learning Commons curricula mapped to academic standards in all 50 states. Sign up by June 30, 2027 for a full year free; FERPA-aligned, no training on educator data.",
          url:"https://www.anthropic.com/news/claude-for-teachers" },
        { name:"Claude Agent SDK", access:["api"], iface:"cli", status:"live", badge:"build your own agents",
          blurb:"SDK for building custom terminal/headless agents on the same harness that powers Claude Code.",
          url:"https://docs.anthropic.com/en/api/agent-sdk" },
        { name:"claude.ai (web app)", access:["subscription"], iface:"web", status:"live", badge:"Free · Pro · Max",
          blurb:"Browser chat + Projects + Artifacts. Model picker: Opus 4.8, Sonnet 5, Haiku 4.5.", url:"https://claude.ai" },
        { name:"Claude on the web (claude.ai/code)", access:["subscription"], iface:"web", status:"live", badge:"cloud coding",
          blurb:"Browser-based coding sessions and cloud agents tied to your subscription.", url:"https://claude.ai/code" },
        { name:"Anthropic Console / Workbench", access:["api"], iface:"web", status:"live", badge:"console.anthropic.com",
          blurb:"API keys, usage, prompt workbench, and the token/cost dashboard.", url:"https://console.anthropic.com" },
        { name:"Claude for Chrome (extension)", access:["subscription"], iface:"extension", status:"live", badge:"Max plan · browser automation",
          blurb:"Claude drives your Chrome tabs — reads pages, fills forms, runs multi-step browser tasks.", url:"https://www.anthropic.com/news/claude-for-chrome" },
        { name:"Claude Desktop (Mac/Windows)", access:["subscription"], iface:"other", status:"live", badge:"native app + MCP",
          blurb:"Desktop app with local MCP server support for tools and file access.", url:"https://claude.ai/download" },
        { name:"Claude API (Messages)", access:["api"], iface:"other", status:"live",
          badge:"Opus 4.8 · Sonnet 5 · Haiku 4.5 · Fable 5* · Mythos 5**",
          blurb:"Raw programmatic access. Fable 5 now permanent for Max/Team Premium at 50% of limits, Pro/Team Standard via usage credits (*, as of Jul 20); Mythos 5 limited to ~100 approved orgs (**).", url:"https://docs.anthropic.com/en/api" },
        { name:"Bedrock · Vertex · Foundry", access:["api"], iface:"other", status:"live", badge:"cloud marketplaces",
          blurb:"Claude via Amazon Bedrock, Google Vertex AI, and Microsoft Foundry for enterprise.", url:"https://docs.anthropic.com/en/api/claude-on-amazon-bedrock" }
      ],
      news: [
        { date:"2026-06-30", sort:"2026-06-30T18:00", cat:"release", flag:"", src:"Anthropic", iface:["web","other"], access:["subscription"],
          title:"Claude Science launches — agentic research for pharma & labs",
          body:"New flagship app wiring 60+ scientific databases and computation tools into one workspace; available to all paid Claude subscribers. Anthropic is also funding up to 50 'AI for Science' projects with up to $30K compute credits each.",
          url:"https://www.technologyreview.com/2026/06/30/1139987/claude-science-is-anthropics-newest-flagship-product/" },
        { date:"2026-06-30", sort:"2026-06-30T16:00", cat:"policy", flag:"", src:"Anthropic", iface:["cli","web","other"], access:["subscription","api"],
          title:"Export controls lifted — Fable 5 returns to general use Jul 1",
          body:"Commerce cleared both models. Fable 5 becomes selectable again across Claude Code, claude.ai, and the API on Wednesday.",
          url:"https://www.cnbc.com/2026/06/30/anthropic-says-trump-admin-has-lifted-export-controls-on-claude-fable-5-and-mythos-5.html" },
        { date:"2026-06-29", sort:"2026-06-29T16:00", cat:"policy", flag:"", src:"Anthropic", iface:["api","other"], access:["api"],
          title:"Mythos 5 cleared for ~100 trusted US critical-infra orgs",
          body:"First restoration signal after June 12 — Mythos 5 redeployable to a limited set of pre-approved organizations via API.",
          url:"https://www.nbcnews.com/business/business-news/commerce-department-gives-green-light-anthropic-bring-back-fable-5-rcna352501" }
      ]
    },

    openai: {
      label:"OpenAI (ChatGPT/Codex)", accent:"#10a37f",
      models: [
        { name:"GPT-5.6 (Sol · Terra · Luna)", access:["subscription","api"], iface:"other", status:"new", badge:"GA Jul 9 · ChatGPT + Codex + API",
          blurb:"Next generation, tiered by capability: Sol (flagship — hardest coding/security), Terra (high-volume business), Luna (fastest/cheapest). Generally available since Jul 9 after the gov-requested preview gate: ChatGPT Plus/Pro/Business/Enterprise get Sol (medium+ reasoning effort), Free/Go get Terra; all three tiers on Codex + API. Sol takes SOTA on Terminal-Bench 2.1 (88.8%). Pricing/1M: Sol $5/$30, Terra $2.50/$15, Luna $1/$6.",
          url:"https://openai.com/index/gpt-5-6/" },
        { name:"Codex CLI", access:["subscription","api"], iface:"cli", status:"live", badge:"GPT-5.6 · GPT-5.5",
          blurb:"OpenAI's terminal coding agent. Runs on a ChatGPT Plus/Pro subscription OR API billing. ~4M weekly devs; GPT-5.6 Sol/Terra/Luna selectable (with per-tier effort levels) since the Jul 9 GA.", url:"https://openai.com/codex/" },
        { name:"ChatGPT (chatgpt.com)", access:["subscription"], iface:"web", status:"live", badge:"GPT-5.6 Sol · Terra (free)",
          blurb:"The flagship web chat. Since the Jul 9 GA, paid tiers run GPT-5.6 Sol and Free/Go users get Terra; the GPT-5.5 family remains selectable (GPT-5.2 and GPT-4.5 retired in June).", url:"https://chatgpt.com" },
        { name:"GPT-Live (voice)", access:["subscription"], iface:"other", status:"new", badge:"full-duplex · GPT-Live-1 / Live-1 mini",
          blurb:"New ChatGPT voice models (launched Jul 8) that listen and speak at the same time, replacing Advanced Voice on iOS/Android/web. Delegates harder questions to GPT-5.5 mid-conversation. Live-1 is the default for paid users; Live-1 mini serves the free tier.",
          url:"https://openai.com/index/introducing-gpt-live/" },
        { name:"ChatGPT Codex (web)", access:["subscription"], iface:"web", status:"live", badge:"cloud coding agent",
          blurb:"Browser-based Codex sessions — delegate coding tasks to cloud agents from your ChatGPT account.", url:"https://openai.com/index/introducing-upgrades-to-codex/" },
        { name:"OpenAI Platform", access:["api"], iface:"web", status:"live", badge:"platform.openai.com",
          blurb:"API keys, usage, Playground, and billing dashboard for developers.", url:"https://platform.openai.com" },
        { name:"ChatGPT Atlas (AI browser)", access:["subscription"], iface:"extension", status:"restricted", badge:"shutting down Aug 9, 2026",
          blurb:"OpenAI's macOS-only AI browser is being sunset — stops working August 9, 2026. Browser-based agentic features move into the unified ChatGPT desktop app (Chat/Work/Codex) plus a ChatGPT/Codex Chrome extension; data won't migrate automatically.", url:"https://www.macrumors.com/2026/07/10/openais-chatgpt-atlas-browser-shutting-down/" },
        { name:"ChatGPT Work", access:["subscription"], iface:"web", status:"new", badge:"agent · launched Jul 9",
          blurb:"New agent tier inside the unified ChatGPT desktop app: takes a goal, gathers info across your connected apps and files, breaks it into steps, and finishes the job on its own — producing sheets, slides, and documents. Free on every plan, including Free.",
          url:"https://openai.com/index/chatgpt-for-your-most-ambitious-work/" },
        { name:"Codex app (desktop)", access:["subscription"], iface:"other", status:"live", badge:"Windows · macOS",
          blurb:"Merged into the unified ChatGPT desktop app on Jul 9 (sits next to Chat & Work) — inline diff editing, GitHub PR review in a sidebar, faster GPT-5.6 Computer Use, multi-repo projects.", url:"https://openai.com/index/chatgpt-for-your-most-ambitious-work/" },
        { name:"ChatGPT Agent / Operator", access:["subscription"], iface:"other", status:"live", badge:"task automation",
          blurb:"Autonomous agent that browses and completes multi-step tasks on your behalf.", url:"https://openai.com/index/introducing-upgrades-to-codex/" },
        { name:"OpenAI API", access:["api"], iface:"other", status:"live", badge:"GPT-5.6 · GPT-5.5 · GPT-5.3-Codex · o-series",
          blurb:"Responses / Chat Completions / Realtime APIs. GPT-5.6 Sol/Terra/Luna generally available since Jul 9.", url:"https://openai.com/index/gpt-5-6/" }
      ],
      news: [
        { date:"2026-06-26", sort:"2026-06-26T09:00", cat:"release", flag:"", src:"OpenAI", iface:["cli","other"], access:["api"],
          title:"GPT-5.6 Sol/Terra/Luna enter limited preview",
          body:"New generation with capability-tier naming (Sol flagship, Terra value, Luna fast). API + Codex to only ~20 trusted orgs after sharing plans with the US government; general availability 'in the coming weeks.' GPT-4.5 retired from ChatGPT the same week.",
          url:"https://venturebeat.com/technology/openai-unveils-gpt-5-6-sol-terra-and-luna-models-but-only-accessible-to-limited-preview-partners-for-now-per-us-gov" },
        { date:"2026-06-29", sort:"2026-06-29T12:00", cat:"agents", flag:"", src:"TechTimes", iface:["cli"], access:["subscription"],
          title:"GPT-5.6 quietly rolled to some Codex users",
          body:"A hidden system prompt exposed OpenAI swapping select Codex sessions onto GPT-5.6 during the preview window.",
          url:"https://www.techtimes.com/articles/319297/20260629/openai-silently-rolled-gpt-56-some-codex-users-hidden-prompt-exposes-swap.htm" },
        { date:"2026-06-01", sort:"2026-06-01T09:00", cat:"release", flag:"", src:"OpenAI", iface:["extension","other"], access:["subscription"],
          title:"ChatGPT + Codex + Atlas merging into one desktop superapp",
          body:"OpenAI confirmed it's unifying its chat, coding agent, and AI browser into a single desktop application; public launch date undisclosed.",
          url:"https://almcorp.com/blog/openai-desktop-superapp-chatgpt-codex-atlas-browser/" },
        { date:"2026-04-23", sort:"2026-04-23T09:00", cat:"release", flag:"", src:"OpenAI", iface:["cli","other"], access:["subscription","api"],
          title:"GPT-5.5 launches as the new Codex backbone",
          body:"First fully retrained base since GPT-4.5, agentic-first. ~4M weekly active Codex developers.",
          url:"https://openai.com/index/introducing-gpt-5-5/" }
      ]
    },

    google: {
      label:"Google (Gemini/Antigravity)", accent:"#4285f4",
      models: [
        { name:"Antigravity CLI", access:["subscription","api"], iface:"cli", status:"live", badge:"replaced Gemini CLI",
          blurb:"Google's terminal agent on the Antigravity harness (Gemini 3.5 Flash). The standalone Gemini CLI was retired June 18, 2026 — migration is complete.", url:"https://developers.googleblog.com/an-important-update-transitioning-gemini-cli-to-antigravity-cli/" },
        { name:"Gemini 3.5 Pro (preview)", access:["api","subscription"], iface:"other", status:"preview", badge:"Vertex preview · 2M ctx · Deep Think",
          blurb:"Frontier Pro model — 2M-token context + Deep Think reasoning. In limited Vertex AI enterprise preview; public launch slipped from June to July 2026.", url:"https://cryptobriefing.com/google-delays-gemini-35-pro-launch-to-july-2026/" },
        { name:"Gemini (gemini.google.com)", access:["subscription"], iface:"web", status:"live", badge:"Gemini 3 Pro · 3.5 Flash",
          blurb:"Consumer web app. Gemini AI Pro / Ultra tiers. 3.5 Flash beats 3.1 Pro on most benchmarks at ~4x speed.", url:"https://blog.google/products-and-platforms/products/gemini/gemini-3/" },
        { name:"Google AI Studio", access:["subscription","api"], iface:"web", status:"live", badge:"aistudio.google.com",
          blurb:"Prototyping playground + API key issuance; hosts Managed Agents, native Android publishing, and the Interactions API.", url:"https://aistudio.google.com" },
        { name:"Gemini in Chrome", access:["subscription"], iface:"extension", status:"live", badge:"browser assistant",
          blurb:"Gemini built into Chrome for page understanding and in-browser assistance.", url:"https://blog.google/products-and-platforms/products/gemini/" },
        { name:"Google Antigravity 2.0", access:["subscription"], iface:"other", status:"new", badge:"agentic dev desktop app",
          blurb:"Agent-first development platform (desktop app) — take an idea to a production-ready app; launched at I/O 2026.", url:"https://antigravity.google/" },
        { name:"Jules (async coding agent)", access:["subscription"], iface:"other", status:"live", badge:"background agent",
          blurb:"Google's asynchronous coding agent that works on tasks in the background and opens PRs.", url:"https://blog.google/technology/developers/gemini-3-developers/" },
        { name:"Gemini in Workspace", access:["subscription"], iface:"other", status:"live", badge:"Gmail · Docs · Sheets",
          blurb:"Gemini embedded across Google Workspace apps.", url:"https://blog.google/products-and-platforms/products/gemini/" },
        { name:"Gemini API", access:["api"], iface:"other", status:"live", badge:"Gemini 3.5 Flash · 3 Pro · 3.5 Pro*",
          blurb:"Programmatic access incl. Managed Agents — spin up tool-using agents in an isolated Linux env with one call. 3.5 Pro (*) is Vertex-preview only until July.", url:"https://blog.google/technology/developers/gemini-3-developers/" },
        { name:"Vertex AI", access:["api"], iface:"other", status:"live", badge:"enterprise cloud",
          blurb:"Gemini models + agent tooling for enterprise on Google Cloud; hosts the Gemini 3.5 Pro preview.", url:"https://cloud.google.com/vertex-ai" }
      ],
      news: [
        { date:"2026-06-23", sort:"2026-06-23T09:00", cat:"release", flag:"", src:"Crypto Briefing", iface:["other"], access:["api","subscription"],
          title:"Gemini 3.5 Pro slips to July — limited Vertex preview for now",
          body:"Google missed its June GA target; 3.5 Pro (2M context, Deep Think) sits in limited Vertex AI enterprise preview while Google refines coding and long-task performance. Pichai on stage: 'give us until next month.'",
          url:"https://cryptobriefing.com/google-delays-gemini-35-pro-launch-to-july-2026/" },
        { date:"2026-05-21", sort:"2026-05-21T09:00", cat:"release", flag:"", src:"Google", iface:["cli","other","web"], access:["subscription","api"],
          title:"Antigravity + Gemini 3.5 Flash headline I/O 2026",
          body:"Agent-first Antigravity platform, Managed Agents in the Gemini API, WebMCP browser standard, and Gemini 3.5 Flash (4x faster, beats 3.1 Pro) anchor the developer keynote.",
          url:"https://blog.google/innovation-and-ai/technology/developers-tools/google-io-2026-developer-highlights/" },
        { date:"2026-05-21", sort:"2026-05-21T08:30", cat:"release", flag:"", src:"Google", iface:["cli"], access:["subscription","api"],
          title:"Gemini CLI is becoming the Antigravity CLI",
          body:"Google transitioned the standalone Gemini CLI into the Antigravity CLI on the unified agent harness; free-tier migration deadline was June 18, 2026.",
          url:"https://developers.googleblog.com/an-important-update-transitioning-gemini-cli-to-antigravity-cli/" }
      ]
    },

    xai: {
      label:"SpaceXAI (Grok)", accent:"#111827",
      models: [
        { name:"Grok Build CLI", access:["subscription","api"], iface:"cli", status:"new", badge:"open source Jul 15 · Apache 2.0",
          blurb:"xAI's terminal coding agent — plan, debug, MCP support, and the /goal long-running autonomous mode. Open-sourced in full (~845K lines of Rust, Apache 2.0) on Jul 15 after the repo-upload privacy scandal; default data retention disabled Jul 12 and previously retained coding data being deleted.", url:"https://simonwillison.net/2026/Jul/15/grok-build/" },
        { name:"Voice Agent Builder", access:["api"], iface:"web", status:"new", badge:"beta · $0.05/min agent audio",
          blurb:"No-code platform for production voice agents on Grok Voice — telephony, knowledge retrieval, tools, guardrails, MCPs, observability, voice cloning, and SIP in one speech-to-speech stack. Launched in beta Jul 1, 2026; free phone number included.",
          url:"https://x.ai/news/grok-voice-agent-builder" },
        { name:"Grok (grok.com)", access:["subscription"], iface:"web", status:"live", badge:"Grok 4.1 · 4.3 beta",
          blurb:"Consumer web app with Auto mode + explicit model picker. Grok 4.3 adds native video input and document generation.", url:"https://grok.com" },
        { name:"xAI Console", access:["api"], iface:"web", status:"live", badge:"console.x.ai · docs.x.ai",
          blurb:"API keys, usage, and developer docs for the Grok models.", url:"https://docs.x.ai/developers/models" },
        { name:"Grok in 𝕏", access:["subscription"], iface:"web", status:"live", badge:"in-platform assistant",
          blurb:"Grok built directly into the 𝕏 (Twitter) app and website, with real-time access to the 𝕏 firehose.", url:"https://x.ai/" },
        { name:"Grok mobile apps", access:["subscription"], iface:"other", status:"live", badge:"iOS · Android",
          blurb:"Grok on iOS and Android for SuperGrok / Premium subscribers.", url:"https://x.ai/" },
        { name:"Grok 4.5", access:["subscription","api"], iface:"other", status:"new", badge:"launched Jul 8 · $2/$6 per 1M",
          blurb:"SpaceXAI's strongest model (V9, ~1.5T) — Cursor-trained, Musk calls it 'Opus-class but faster and lower cost.' ~80 tok/s, ~4.2x fewer output tokens per task than Opus 4.8 max. Default in Grok Build; live in Cursor (all plans), the API/console, and major gateways. EU rollout mid-July.", url:"https://x.ai/news/grok-4-5" },
        { name:"xAI API", access:["api"], iface:"other", status:"live", badge:"Grok 4.5 · Grok 4 · grok-code-fast-1 · Grok Build 0.1",
          blurb:"OpenAI-compatible endpoint at api.x.ai/v1 with usage-based pricing; drop-in for existing OpenAI SDK code.", url:"https://x.ai/api" },
        { name:"Live Search API", access:["api"], iface:"other", status:"live", badge:"web + 𝕏 + news",
          blurb:"Real-time search over the web, 𝕏, and news sources — the freshest-data edge among the big providers.", url:"https://x.ai/api" }
      ],
      news: [
        { date:"2026-06-28", sort:"2026-06-28T12:00", cat:"release", flag:"", src:"xAI", iface:["web","other"], access:["subscription"],
          title:"Grok 4.5 (V9, ~1.5T) — Musk claims Opus-level, private beta",
          body:"Internal SpaceX/Tesla testing; 'early evals show performance close to, perhaps exceeding Opus' — no independent benchmark yet. V9 is ~3x the V8-small base and trained with Cursor data. xAI plans a from-scratch model every month through end of 2026; Grok 5 is reportedly training on Colossus 2.",
          url:"https://cybernews.com/ai-news/musk-grok-4-5-private-beta-superior-claude-opus/" },
        { date:"2026-06-26", sort:"2026-06-26T10:00", cat:"agents", flag:"", src:"DevOps.com", iface:["cli","other"], access:["subscription","api"],
          title:"Grok Build 0.1 opens to developers via the xAI API",
          body:"The coding model powering the Grok Build CLI is now available on the API (public beta) — no SuperGrok/Premium+ needed to build on it.",
          url:"https://devops.com/xai-opens-grok-build-0-1-to-developers-via-api/" },
        { date:"2026-04-17", sort:"2026-04-17T09:00", cat:"release", flag:"", src:"xAI", iface:["web"], access:["subscription"],
          title:"Grok 4.3 Beta — native video input, document generation, better tool-calling",
          body:"Improved architecture (Dec 2025 knowledge cutoff), PDFs/spreadsheets/slides generation, and stronger tool use.",
          url:"https://www.lorka.ai/ai-models/xai" }
      ]
    }
  }
};
